version: '3'
services:
  vendas-web:
    image: maven
    depends_on:
      - "db"
    volumes:
      - ".:/deploy"
    working_dir: "/deploy"
    ports:
      - "8088:8080"
    command: bash -c "mvn clean && mvn install && java -jar target/vendasweb-0.0.1-SNAPSHOT.jar"
    links:
      - db
    container_name: VendasWeb 
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=vendasweb
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./others/docker/mysql_volume:/var/lib/mysql  
    container_name: db  
