version: '3'
services:
  vendas-web:
    build:
      context: ./
      dockerfile: ./DockerFile
    image: vendasweb-api
    volumes:
      - ".:/deploy"
    ports:
      - "8088:8080"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  #  command: bash -c "mvn clean && mvn install"  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=vendasweb
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
     - ./others/docker/mysql_volume:/var/lib/mysql  
    container_name: db  
