FROM openjdk:11

ARG PROFILE
ARG ADDITIONAL_OPTS

ENV PROFILE=${PROFILE}
ENV ADDITIONAL_OPTS=${ADDITIONAL_OPTS}

WORKDIR /opt/starter

COPY /target/vendasweb*.jar vendasweb.jar

SHELL ["/bin/sh", "-c"]

EXPOSE 8088
EXPOSE 5005

CMD mvn clean install

CMD java ${ADDITIONAL_OPTS} -jar  vendasweb.jar --spring.profiles.active=${PROFILE}